### PR TITLE
Separate non-canon feature names into new layer

### PR DESCRIPTION
**Pull request by hellricer**
The Combined_Placenames_260312 shapefile contains lots of great information, however it doesn't distinguish between names from “canon” sources and the ones from MERP.

I propose to separate MERP features into a separate shapefile.

### CODE REVIEW

**Comment by jvangeld** [comment]
Could we add an attribute to Combined_Placenames_260312.dbf for the source information for each feature? That way people could do a definition query on the layer if they want to limit their view to a certain source. It could be a really short text field holding things like 'LOTR', 'MERP', 'SILM'. Now that you have the features broken out, it shouldn't be too difficult to fill that attribute in when the features are combined together again.

Also, we can get rid of the date and just call it Combined_Placenames.dbf

**Comment by RobSis** [comment]
Yeah, introducing new field would be trivial at this point.

But I'm not sure I can distinguish between LOTR, Silmarillion and Hobbit features in any easy way... 

For now, I will set the new field to MERP and leave it empty for “canon” features.

**Comment by hellricer** [comment]
Yeah, introducing new field would be trivial at this point.

But I'm not sure I can distinguish between LOTR, Silmarillion and Hobbit features in any easy way...

For now, I will set the new field to MERP and leave it empty for “canon” features.

**Comment by jvangeld** [comment]
Awesome, thank you!

**Pull request merged**
